server:
  port: 7777
  error:
    include-stacktrace: always
  servlet:
    context-path:

logging:
  level:
    root: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  application:
    name: j-sso
  mvc:
    static-path-pattern: /static/**
    cors:
      configs:
        - pattern: /**
          allowed-origins: "http://127.0.0.1:8080,http://localhost:8080,http://localhost:7778,http://localhost:7979"
          allowed-headers: "*"
          exposed-headers: "*"
          allowed-methods: "*"
          allow-credentials: true
  web:
    resources:
      static-locations: classpath:static
  session:
    timeout: 1800                 # Время жизни сессии (в секундах)
    redis:
      flush-mode: on_save         # Указываем, когда изменения сеанса записываются в хранилище (immediate или on_save)
      namespace: j-sso:session    # Пространство имен для ключей, используемых для хранения сессий.
      save-mode: on_set_attribute # Определяет в какой момент происходит сохранение изменений сессии (on_set_attribute, on_get_attribute, always)
  config:
    import:
      - application-data.yml
      - application-security.yml
  task:
    scheduling:
      pool:
        size: 2

yandex-avatar-url: https://avatars.yandex.net/get-yapic/{avatarId}/islands-retina-50

d-email:
  email: ${JSSO_SMTP_EMAIL}
  password: ${JSSO_SMTP_EMAIL_PASSWORD}
  host: smtp.jino.ru
  port: 587

otp-store:
  cookie-name: j-sso-temporary-session
  cookie-domain: localhost
  cookie-max-age: 180

file-store:
  base-path: ~/j-sso-file-store

scheduled-tasks:
  delete-old-events:
    cron: '@daily'
    saved-period-days: 1
  notify-delete-users:
    cron: '*/10 * * * * *'

rest-clients:
  service-client-connection-timeout: 10000
  service-client-request-timeout: 30000