spring:
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777${server.servlet.context-path}
        introspection-endpoint: /oauth2/token-info
        reset-password-endpoint: /client/auth/reset-password
        authentication-success-url: http://localhost:7777${server.servlet.context-path}/client/oauth/continue
        saved-request-url-starts-with: http://localhost:7777${server.servlet.context-path}/oauth2/authorize
        custom-handler-header-name: J-Sso-Next-Location
        authorization-ttl: 10800000
        authorization-consent-ttl: 10800000
      client:
        registration:
          github:
            clientId: ${JSSO_GITHUB_CLIENT_ID}
            clientSecret: ${JSSO_GITHUB_CLIENT_SECRET}
            redirect-uri: http://localhost:7777/${server.servlet.context-path}/login/oauth2/code/github

          google:
            clientId: ${JSSO_GOOGLE_CLIENT_ID}
            clientSecret: ${JSSO_GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:7777/${server.servlet.context-path}/login/oauth2/code/google
            scope:
              - email
              - profile

          yandex:
            provider: yandex
            clientId: ${JSSO_YANDEX_CLIENT_ID}
            clientSecret: ${JSSO_YANDEX_CLIENT_SECRET}
            redirect-uri: http://localhost:7777/${server.servlet.context-path}/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info